---
title: "Tu et al. vis"
output: html_notebook
---

```{r}
rm(list=ls())
library(tidyverse)
library(reshape2)
```

Manipulate data
```{r}
df <- read.csv("../data/tu_et_al_2019/inputfile.csv", header = F)
full_df <- read.csv("../data/tu_et_al_2019/GSE75748_sc_time_course_ec.csv") %>% 
  t() %>% 
  as.data.frame()
lnames <- full_df[1, ]
full_df <- full_df[-1, ]
lnames <- map_chr(lnames, ~as.character(.))
colnames(full_df) <- lnames

full_df <- full_df %>% 
  rownames_to_column(var = "temp") %>% 
  mutate(time=substr(temp, 4, 5)) %>% 
  dplyr::select(-temp) %>% 
  mutate(time=as.numeric(time)) %>% 
  mutate_if(function(x) !is.numeric(x), as.numeric)

# write.csv(full_df, "../data/tu_et_al_2019/GSE75748_sc_time_course_ec_processed.csv")
```

Plot data at each time
```{r}
full_df %>% 
  group_by(time) %>% 
  count()

full_df %>% 
  ggplot(aes(x=CDH1, y=KLF8)) +
  geom_point() +
  geom_density_2d(h=200) +
  facet_wrap(~time)

full_df %>% 
  ggplot(aes(x=CDH1, y=ZEB1)) +
  geom_point() +
  geom_density_2d(h=200) +
  facet_wrap(~time)

full_df %>% 
  ggplot(aes(x=KLF8, y=ZEB1)) +
  geom_point() +
  geom_density_2d(h=200) +
  facet_wrap(~time)
```

Look only at 12 and 72 hours
```{r}
full_df %>% 
  filter((time==12|time==72)) %>% 
  ggplot(aes(x=CDH1, y=KLF8)) +
  geom_point() +
  geom_density_2d(h=200) +
  facet_wrap(~time) +
  facet_wrap(~time, scales="free")

full_df %>% 
  filter((time==12|time==72)) %>%
  ggplot(aes(x=CDH1, y=ZEB1)) +
  geom_point() +
  geom_density_2d(h=200) +
  facet_wrap(~time) +
  facet_wrap(~time, scales="free")

full_df %>% 
  filter((time==12|time==72)) %>%
  ggplot(aes(x=KLF8, y=ZEB1)) +
  geom_point() +
  geom_density_2d(h=200) +
  facet_wrap(~time, scales="free")
```


```{r}
library(fitdistrplus)
tmp1 <- full_df %>% 
  filter(time==12) %>%
  pull(CDH1)
hist(tmp1)
descdist(tmp1)
fit <- fitdist(tmp1/100, "norm")
fit

tmp <- full_df %>% 
  filter(time==72) %>%
  pull(CDH1)
qplot(tmp)

descdist(tmp)

fit <- fitdist(tmp/100, "gamma")

hist(rgamma(10000, 1.7, 0.84))

tmp <- full_df %>% 
  filter(time==36) %>%
  pull(CDH1)
qplot(tmp)

descdist(tmp)

fit <- fitdist(tmp/100, "gamma")
fit

tmp1 <- full_df %>% 
  filter(time==72) %>%
  pull(KLF8)
hist(tmp1/100)
descdist(tmp1)
fit <- fitdist(tmp1/100, "norm")
fit
```


Fit using multivariate normal
```{r}
df_12 <- full_df %>% 
  select(time, CDH1)%>% 
  filter(time==12)
df_72 <- full_df %>% 
  select(time, KLF8)%>% 
  filter(time==72)
df_tot <- df_12

cov_12 <- cov(df_12)
mu_12 <- colMeans(df_12)

df_72 <- full_df %>% 
  select(CDH1, KLF8, time) %>%
  filter((time==72)) %>% 
  select(-time) %>%
  mutate_all(.funs=function(x) x/100)
cov_72 <- cov(df_72)
mu_72 <- colMeans(df_72)
```

